version: "3.8"

services:
  localstack:
    privileged: true
    restart: always
    container_name: localstack_main
    image: localstack/localstack:0.11.2
    ports:
      - 4566:4566
      - 4571:4571
    environment:
      - SERVICES=sns,sqs
      - DEBUG=${DEBUG- }
      - TEST_AWS_ACCOUNT_ID=000000000000
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/tmp/localstack
    volumes:
      - localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  localstack:
